pipeline {
  agent {
    docker {
      image 'maven:3.8.6-openjdk-11'
    }
  }
  stages {
    stage('Run Gatling Test') {
      steps {
        sh 'mvn gatling:test'
      }
    }
    stage('Saving folder') {
        def gatlingFolder = sh(script: "ls target/gatling", returnStdout: true).trim()
        echo "Gatling folder found: ${gatlingFolder}"
    }
  }
}
