#!groovy

node {
    docker.image('denvazh/gatling:latest') {
        stage('version') {
            sh 'echo version'
        }

        stage('Running') {
            sh 'mvn gatling:test'
        }
    }
}