pipeline {
  agent {
    docker {
      image 'maven:3.8.6-openjdk-11'
    }
  }
  stages {
    stage('Run Gatling Test') {
      steps {
        sh 'mvn gatling:test'
      }
    }
    stage('Saving folder') {
        steps {
            script {
                def gatlingFolder = sh(script: "cat target/gatling/lastRun.txt", returnStdout: true).trim()
                echo "Gatling folder found: ${gatlingFolder}"

                sh "cd target/gatling && zip -r ${gatlingFolder}.zip ${gatlingFolder}"

                archiveArtifacts artifacts: "target/gatling/${gatlingFolder}/**", onlyIfSuccessful: true
            }
        }
    }
  }
}
